web_crowd_add:
    path:     /add
    defaults: { _controller: WEBCrowdBundle:KickUp:add }
web_crowd_about:
    path:     /about
    defaults: { _controller: WEBCrowdBundle:KickUp:about }

web_crowd_contact:
    path:     /contact
    defaults: { _controller: WEBCrowdBundle:KickUp:contact }
    requirements:
web_crowd_homepage:
    path:     /{page}
    defaults: { _controller: WEBCrowdBundle:KickUp:index, page : 1 }
web_crowd_view:
    path:     /projet/{id}
    defaults: { _controller: WEBCrowdBundle:KickUp:view}
    requirements:
        id:  \d 
web_crowd_edit:
    path:     /edit/{id}
    defaults: { _controller: WEBCrowdBundle:KickUp:edit}
    requirements:
        id:  \d+
web_crowd_delete:
    path:     /delete/{id}
    defaults: { _controller: WEBCrowdBundle:KickUp:delete}
    requirements:
        id:  \d+   
web_crowd_view:
    path:     /delete/{id}
    defaults: { _controller: WEBCrowdBundle:KickUp:delete}
    requirements:
        id:  \d+  
web_crowd_hello:
    path:     /hello/{name}
    defaults: { _controller: WEBCrowdBundle:Default:index }
